# This is the config file for demultiplx-usearch.sb #

# NOTE!!! Modify all the PATHs below accordingly. 

# USEARCH binary
export usearch11="/mnt/research/bonito_lab/usearch/usearch11.0.667_i86linux64"

# Main file paths
project_dir="/mnt/home/benucci/Demultiplex-USEARCH"

# Raw fast files. Remember that USEARCH does NOT support compressed files e.g. fastq.gz
R1="/mnt/research/plb847_lab/MSU_original_miseq-runs/20160812_Amplicon_PE/16S_amplicon_library_384samples_pooled_NoIndex_L001_R1_001.fastq"
R2="/mnt/research/plb847_lab/MSU_original_miseq-runs/20160812_Amplicon_PE/16S_amplicon_library_384samples_pooled_NoIndex_L001_R2_001.fastq"
I1="/mnt/research/plb847_lab/MSU_original_miseq-runs/20160812_Amplicon_PE/16S_amplicon_library_384samples_pooled_NoIndex_L001_I1_001.fastq"

# bacrodes in a .fasta format
index="/mnt/home/benucci/Demultiplex-USEARCH/barcodes/index_16S_AU.fasta"

# gzip output fastq file? if so add "yes"
gzipped=yes

