# This is the config file for demultiplx-usearch.sb #

# NOTE!!! Modify all the PATHs below accordingly. 

# Main file paths
project_dir="/mnt/home/benucci/Demultiplex-USEARCH/"

# Raw fast files. Remember that USEARCH does NOT support compressed files e.g. fastq.gz
R1="/mnt/research/bonito_lab/Benucci/miseq_ITS_Australia_Fiji_LSU/AustraliaFiji_ITSandLSU_NoIndex_L001_R1_001.fastq"
R2="/mnt/research/bonito_lab/Benucci/miseq_ITS_Australia_Fiji_LSU/AustraliaFiji_ITSandLSU_NoIndex_L001_R3_001.fastq"
I1="/mnt/research/bonito_lab/Benucci/miseq_ITS_Australia_Fiji_LSU/AustraliaFiji_ITSandLSU_NoIndex_L001_R2_001.fastq"

# bacrodes in a .fasta format
index="/mnt/home/benucci/Demultiplex-USEARCH/aus_ITS_barcodes.fasta"
