# This is the config file for demultiplx-usearch.sb #

# NOTE!!! Modify all the PATHs below accordingly. 

# Main file paths
project_dir="/mnt/home/benucci/Demultiplex-USEARCH"

# Raw fast files
R1="/mnt/home/benucci/Demultiplex-USEARCH/rawdata/*R1_001.fastq"
R2="//mnt/home/benucci/Demultiplex-USEARCH/rawdata/*R2_001.fastq"
I1="/mnt/home/benucci/Demultiplex-USEARCH/rawdata/*I1_001.fastq"

# bacrodes in a .fasta format
index="/mnt/home/benucci/Demultiplex-USEARCH/rawdata/barcodes_16s_preserv_maturity.fasta"
